// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvzclugjhvszjqjetdrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2emNsdWdqaHZzempxamV0ZHJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwODczNzIsImV4cCI6MjA3MzY2MzM3Mn0.a-OHko-7KPdwUSZy-xr37iCzApYGUozu9gytFlU5nM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});